"""
Central niche registry — ONE source of truth for every local-business niche.
design_dna / asset_lib / copywriter / reference_scout all read from here, so adding a niche
= editing ONE place.

Each niche -> an ARCHETYPE (design prefs + effect bias) + its own keywords + copy.
Helpers expose the per-module shapes:
  DESIGN_PREFS[canon] = {font, scheme, layout}   (design_dna)
  EFFECT_BIAS[canon]  = [tags]                    (asset_lib)
  COPY[canon]         = {eyebrow, headlines, cta, about, faq}   (copywriter)
  NICHE_WORDS         = [all keywords]            (reference_scout)
  resolve(text)       -> canonical key or ""
"""

# ── design + effect archetypes (font moods / palette schemes / layouts / effect tags) ──
ARCHETYPES = {
    "fitness":      {"font": ["bold", "industrial", "sport", "tech", "loud", "display"], "scheme": ["dark"],
                     "palette": ["bold", "energetic", "masculine", "sporty", "vibrant"],
                     "layout": ["centered-massive-type", "scroll-snap-sections", "full-bleed-gradient", "bento-grid"],
                     "effects": ["bold", "dark", "kinetic", "interactive"]},
    "trade":        {"font": ["bold", "industrial", "clean", "modern"], "scheme": ["light", "dark"],
                     "palette": ["masculine", "industrial", "rugged", "corporate", "trust", "professional"],
                     "layout": ["split-hero", "centered-massive-type", "bento-grid"],
                     "effects": ["bold", "interactive", "essential"]},
    "beauty":       {"font": ["elegant", "editorial", "calm", "light", "fashion"], "scheme": ["light"],
                     "palette": ["feminine", "soft", "elegant", "luxe", "beauty"],
                     "layout": ["magazine-editorial", "centered-massive-type", "asymmetric-offset"],
                     "effects": ["calm", "soft", "premium"]},
    "medical":      {"font": ["clean", "modern", "calm", "editorial"], "scheme": ["light"],
                     "palette": ["clinical", "clean", "trust", "calm", "medical"],
                     "layout": ["split-hero", "centered-massive-type", "magazine-editorial"],
                     "effects": ["calm", "minimal", "essential", "premium"]},
    "food":         {"font": ["warm", "editorial", "elegant", "modern"], "scheme": ["light"],
                     "palette": ["warm", "natural", "inviting", "hospitality", "premium"],
                     "layout": ["magazine-editorial", "asymmetric-offset", "full-bleed-gradient"],
                     "effects": ["soft", "editorial", "premium"]},
    "professional": {"font": ["classic", "editorial", "clean", "modern"], "scheme": ["light"],
                     "palette": ["corporate", "professional", "trust", "premium", "elegant"],
                     "layout": ["magazine-editorial", "split-hero"],
                     "effects": ["minimal", "editorial", "essential"]},
    "events":       {"font": ["elegant", "editorial", "premium", "fashion", "display"], "scheme": ["light", "dark"],
                     "palette": ["luxe", "premium", "elegant", "feminine"],
                     "layout": ["full-bleed-gradient", "magazine-editorial", "asymmetric-offset"],
                     "effects": ["premium", "soft", "headline"]},
    "tech":         {"font": ["tech", "modern", "geometric", "bold"], "scheme": ["dark", "light"],
                     "palette": ["tech", "creative", "bold", "vibrant", "premium"],
                     "layout": ["bento-grid", "split-hero", "full-bleed-gradient", "scroll-snap-sections"],
                     "effects": ["tech", "modern", "bold"]},
}

QUOTE_FAQ = [("How do I get a quote?", "Tap any button and tell us about the job — most quotes are same-day."),
             ("Are you licensed and insured?", "Yes, fully licensed and insured — we'll share details on request."),
             ("Do you offer emergency service?", "Yes, we prioritize urgent jobs whenever possible.")]

# ── the niches (archetype + keywords + copy) ─────────────────────────────────────
NICHES = {
    # FITNESS / WELLNESS MOVEMENT
    "gym": {"a": "fitness", "kw": ["gym", "fitness", "crossfit", "strength", "personal trainer", "bootcamp"],
            "cta": "Book a Free Session", "eyebrow": ["RESULTS WITHOUT GUESSWORK", "COACHED, NOT CROWDED"],
            "headlines": ["Get strong. Stay strong.", "Train with a plan that actually works.", "Your strongest self starts here."],
            "about": "We coach busy people to move better and get measurably stronger — no fads, no guesswork, just programmed training and coaches who watch every rep.",
            "faq": [("Do I need experience?", "No — we start with an assessment and meet you at your level."),
                    ("How long are sessions?", "45–60 minutes, built to fit a workday."),
                    ("Can I try first?", "Yes, your first session is free.")]},
    "yoga": {"a": "beauty", "kw": ["yoga", "pilates", "barre", "meditation"],
             "cta": "Book a Class", "eyebrow": ["BREATHE · MOVE · RESTORE", "ALL LEVELS WELCOME"],
             "headlines": ["Find your center.", "Strength, breath, and calm.", "Move with intention."],
             "about": "A calm studio for every body and every level. Build strength and flexibility while leaving the noise of the day at the door.",
             "faq": [("I'm a beginner — is that okay?", "Absolutely. We have classes designed for first-timers."),
                     ("What should I bring?", "Just comfortable clothes — mats and props are provided."),
                     ("Do you offer memberships?", "Yes, plus drop-in and class packs.")]},

    # MEDICAL / HEALTH
    "dental": {"a": "medical", "kw": ["dental", "dentist", "orthodontic", "orthodontist", "invisalign"],
               "cta": "Book Appointment", "eyebrow": ["GENTLE · MODERN · FAMILY-FRIENDLY", "NEW PATIENTS WELCOME"],
               "headlines": ["A dentist you'll actually look forward to.", "Healthy smiles, gently done.", "Modern care for your whole family."],
               "about": "We blend gentle, modern dentistry with honest, plain-English care — from routine cleanings to cosmetic work, comfortable and clearly informed at every step.",
               "faq": [("Do you take my insurance?", "We work with most major plans — ask and we'll verify your coverage."),
                       ("Accepting new patients?", "Yes, and new-patient visits book easily online."),
                       ("Does it hurt?", "We prioritize comfort with gentle techniques.")]},
    "chiropractor": {"a": "medical", "kw": ["chiropractor", "chiropractic", "spine", "adjustment"],
                     "cta": "Book Appointment", "eyebrow": ["MOVE BETTER, FEEL BETTER", "RELIEF THAT LASTS"],
                     "headlines": ["Get back to pain-free living.", "Care for how you move.", "Feel the difference."],
                     "about": "Hands-on chiropractic care focused on lasting relief, not just a quick crack — we treat the cause so you can move freely again.",
                     "faq": [("Is the first visit an exam?", "Yes — we assess before we ever adjust."),
                             ("Do you take insurance?", "Most major plans accepted; we'll verify yours."),
                             ("How many visits will I need?", "We'll give you an honest plan after the exam.")]},
    "physical-therapy": {"a": "medical", "kw": ["physical therapy", "physiotherapy", "rehab", "sports medicine"],
                         "cta": "Book Evaluation", "eyebrow": ["RECOVER STRONGER", "ONE-ON-ONE CARE"],
                         "headlines": ["Recover. Rebuild. Return.", "Get back to what you love.", "Movement is medicine."],
                         "about": "One-on-one physical therapy that gets you back to full strength with a clear, personalized plan — no crowded clinics, no guesswork.",
                         "faq": [("Do I need a referral?", "Often not — ask us about direct access in your state."),
                                 ("How long are sessions?", "Typically 45–60 minutes, one-on-one."),
                                 ("Do you take insurance?", "Yes, most major plans.")]},
    "medspa": {"a": "beauty", "kw": ["med spa", "medspa", "medical spa", "botox", "filler", "aesthetic", "injectable"],
               "cta": "Book a Consultation", "eyebrow": ["LOOK LIKE YOU, REFRESHED", "RESULTS, NATURALLY"],
               "headlines": ["Confidence, refined.", "Look refreshed, never overdone.", "Your best skin starts here."],
               "about": "Medical-grade aesthetics with a natural-results philosophy — expert injectors and modern treatments in a calm, judgment-free setting.",
               "faq": [("Is there a consultation?", "Yes — every treatment starts with a personalized consult."),
                       ("Is there downtime?", "Most treatments have little to none; we'll tell you exactly what to expect."),
                       ("Who performs treatments?", "Licensed medical professionals, always.")]},
    "dermatology": {"a": "medical", "kw": ["dermatology", "dermatologist", "skin clinic"],
                    "cta": "Book Appointment", "eyebrow": ["HEALTHY SKIN, EXPERT CARE", "MEDICAL & COSMETIC"],
                    "headlines": ["Skin care, expertly done.", "Healthy skin for life.", "Care your skin can feel."],
                    "about": "Board-certified dermatology for medical and cosmetic needs — clear answers, modern treatments, and care tailored to your skin.",
                    "faq": [("Do you treat both medical and cosmetic?", "Yes, from skin checks to cosmetic treatments."),
                            ("Do you take insurance?", "Medical visits, yes — we'll verify your plan."),
                            ("How soon can I be seen?", "We keep appointments moving — ask about availability.")]},
    "veterinary": {"a": "medical", "kw": ["veterinary", "veterinarian", "vet", "animal hospital", "pet clinic"],
                   "cta": "Book a Visit", "eyebrow": ["CARE THEY DESERVE", "GENTLE WITH EVERY PET"],
                   "headlines": ["Care your pet can trust.", "Healthy pets, happy families.", "Gentle care, every visit."],
                   "about": "Compassionate veterinary care for the whole family — from wellness visits to urgent needs, with a calm, low-stress experience for your pet.",
                   "faq": [("Do you see new patients?", "Yes — we'd love to meet your pet."),
                           ("Do you handle emergencies?", "Ask about same-day and urgent care availability."),
                           ("What animals do you treat?", "Primarily dogs and cats — call to confirm others.")]},
    "optometry": {"a": "medical", "kw": ["optometry", "optometrist", "eye care", "eye doctor", "vision"],
                  "cta": "Book an Eye Exam", "eyebrow": ["SEE CLEARLY", "EXAMS & EYEWEAR"],
                  "headlines": ["See your best.", "Clear vision, expert care.", "Eye care made easy."],
                  "about": "Comprehensive eye exams and a curated eyewear selection — modern technology and unhurried, personal care.",
                  "faq": [("How often should I get an exam?", "Most adults: yearly. We'll advise based on your needs."),
                          ("Do you carry frames?", "Yes, a curated in-house selection."),
                          ("Do you take vision insurance?", "Most plans — we'll verify yours.")]},
    "clinic": {"a": "medical", "kw": ["clinic", "urgent care", "family medicine", "primary care", "medical center"],
               "cta": "Book a Visit", "eyebrow": ["CARE WHEN YOU NEED IT", "WALK-INS WELCOME"],
               "headlines": ["Care, close to home.", "Feel better, faster.", "Healthcare without the hassle."],
               "about": "Friendly, modern care for everyday health needs — short waits, clear communication, and a team that treats you like a person.",
               "faq": [("Do you take walk-ins?", "Yes, plus easy online booking."),
                       ("Do you take insurance?", "Most major plans — we'll verify yours."),
                       ("What do you treat?", "Everyday illness, injuries, physicals, and more.")]},

    # BEAUTY / GROOMING
    "spa": {"a": "beauty", "kw": ["spa", "day spa", "wellness", "massage"],
            "cta": "Book Appointment", "eyebrow": ["WHERE CALM BECOMES RITUAL", "ESCAPE THE EVERYDAY"],
            "headlines": ["Unwind, fully.", "Your calm, restored.", "Slow down and breathe."],
            "about": "A serene escape for massage, facials, and total relaxation — thoughtful treatments in a space designed to melt the day away.",
            "faq": [("Should I book ahead?", "Yes — weekends fill quickly."),
                    ("Can I buy gift cards?", "Yes, perfect for any occasion."),
                    ("What if I'm running late?", "Let us know — we'll do our best to accommodate.")]},
    "salon": {"a": "beauty", "kw": ["salon", "hair salon", "hairdresser", "stylist", "blowout", "color"],
              "cta": "Book Appointment", "eyebrow": ["HAIR YOU'LL LOVE", "STYLE, ELEVATED"],
              "headlines": ["Hair that turns heads.", "Your look, perfected.", "Walk in. Glow out."],
              "about": "A modern salon where skilled stylists craft cuts and color tailored to you — relaxed, friendly, and always on-trend.",
              "faq": [("Do you offer consultations?", "Yes — free before every color or restyle."),
                      ("How do I book?", "Online in under a minute, or give us a call."),
                      ("Do you do corrective color?", "Yes — bring us your inspo photos.")]},
    "barber": {"a": "beauty", "kw": ["barber", "barbershop", "mens grooming", "fade", "shave"],
               "cta": "Book a Cut", "eyebrow": ["SHARP EVERY TIME", "CLASSIC MEETS MODERN"],
               "headlines": ["Look sharp. Feel sharper.", "Your best cut, every time.", "Precision grooming."],
               "about": "A neighborhood barbershop built on precision cuts, hot-towel shaves, and good conversation — walk out looking your best.",
               "faq": [("Do you take walk-ins?", "Yes, but booking guarantees your slot."),
                       ("Do you do beard work?", "Trims, shaping, and hot-towel shaves."),
                       ("Kids' cuts?", "Absolutely.")]},
    "nails": {"a": "beauty", "kw": ["nail salon", "nails", "manicure", "pedicure"],
              "cta": "Book Appointment", "eyebrow": ["POLISHED TO PERFECTION", "CLEAN · RELAXING · YOU"],
              "headlines": ["Nails that make the look.", "Treat yourself.", "Polished, every time."],
              "about": "Meticulous manicures and pedicures in a spotless, relaxing space — quality products and detail-obsessed technicians.",
              "faq": [("Do you take walk-ins?", "Yes, though booking is recommended."),
                      ("Are tools sanitized?", "Always — strict hygiene every service."),
                      ("Do you do nail art?", "Yes, simple to elaborate.")]},
    "tattoo": {"a": "beauty", "kw": ["tattoo", "tattoo studio", "piercing", "ink"],
               "cta": "Book a Consultation", "eyebrow": ["ART THAT LASTS", "CUSTOM · CLEAN · BOLD"],
               "headlines": ["Wear your story.", "Custom ink, done right.", "Art that lasts a lifetime."],
               "about": "A clean, welcoming studio for custom tattoo work — talented artists who bring your idea to life and a hygiene standard you can trust.",
               "faq": [("Do you do custom designs?", "Yes — every piece starts with a consult."),
                       ("Is it safe and sterile?", "Single-use needles, strict sanitation, always."),
                       ("Do you tattoo minors?", "No — must be of legal age with valid ID.")]},

    # FOOD & DRINK
    "coffee": {"a": "food", "kw": ["coffee", "cafe", "espresso", "roaster", "coffee shop"],
               "cta": "Order Online", "eyebrow": ["SMALL-BATCH · LOCALLY ROASTED", "YOUR THIRD PLACE"],
               "headlines": ["Coffee worth slowing down for.", "Roasted with intent.", "Your new favorite morning."],
               "about": "We roast in small batches and brew every cup to order — whether grabbing a pour-over or settling in, you're always welcome here.",
               "faq": [("Do you sell beans?", "Yes — fresh-roasted, whole or ground."),
                       ("Can I order ahead?", "Yes, skip the line with online ordering."),
                       ("Do you cater?", "Our coffee cart can come to you.")]},
    "restaurant": {"a": "food", "kw": ["restaurant", "bistro", "eatery", "dining", "grill", "kitchen"],
                   "cta": "Reserve a Table", "eyebrow": ["FRESH · LOCAL · MADE TO ORDER", "TASTE THE DIFFERENCE"],
                   "headlines": ["Food made to remember.", "Fresh, local, unforgettable.", "Come hungry. Leave happy."],
                   "about": "A neighborhood favorite serving fresh, made-from-scratch dishes in a warm, welcoming space — food that brings people back.",
                   "faq": [("Do you take reservations?", "Yes — book a table in seconds."),
                           ("Do you offer takeout?", "Yes, plus catering for events."),
                           ("Any dietary options?", "Vegetarian and gluten-friendly dishes available.")]},
    "bakery": {"a": "food", "kw": ["bakery", "patisserie", "pastry", "cake shop", "bread"],
               "cta": "Order Online", "eyebrow": ["BAKED FRESH DAILY", "FROM SCRATCH, ALWAYS"],
               "headlines": ["Fresh from the oven.", "Baked with love daily.", "Your sweet spot."],
               "about": "Everything baked fresh daily from scratch — breads, pastries, and custom cakes made with real ingredients and real care.",
               "faq": [("Do you do custom cakes?", "Yes — order ahead for events."),
                       ("Can I order online?", "Yes, for pickup or local delivery."),
                       ("Any gluten-free options?", "Select items — ask in store.")]},
    "catering": {"a": "food", "kw": ["catering", "caterer", "private chef", "food truck"],
                 "cta": "Request a Quote", "eyebrow": ["EVENTS, DELICIOUSLY DONE", "STRESS-FREE CATERING"],
                 "headlines": ["Catering they'll talk about.", "Great food, zero stress.", "We bring the feast."],
                 "about": "Full-service catering for events of any size — fresh menus, professional service, and a team that handles every detail.",
                 "faq": [("How far ahead should I book?", "The sooner the better, especially weekends."),
                         ("Can you handle dietary needs?", "Yes — we customize every menu."),
                         ("Do you provide staff?", "Yes, servers and setup available.")]},
    "florist": {"a": "food", "kw": ["florist", "flowers", "flower shop", "floral"],
                "cta": "Order Flowers", "eyebrow": ["FRESH BLOOMS DAILY", "ARRANGED WITH LOVE"],
                "headlines": ["Flowers that say it best.", "Blooms for every moment.", "Fresh, always."],
                "about": "Hand-arranged bouquets and event florals using the freshest seasonal blooms — beautiful flowers for every occasion, delivered with care.",
                "faq": [("Do you deliver?", "Yes, locally — same-day when ordered early."),
                        ("Do you do weddings?", "Yes — book a floral consultation."),
                        ("Can I order online?", "Yes, anytime.")]},

    # HOME / TRADE SERVICES
    "hvac": {"a": "trade", "kw": ["hvac", "heating", "cooling", "air conditioning", "furnace", "ac repair"],
             "cta": "Get a Free Quote", "eyebrow": ["COMFORT, GUARANTEED", "24/7 EMERGENCY SERVICE"],
             "headlines": ["Comfortable, all year round.", "Heating & cooling done right.", "Fast, honest HVAC service."],
             "about": "Licensed HVAC pros for repair, install, and maintenance — upfront pricing, fast response, and systems that keep you comfortable in every season.",
             "faq": QUOTE_FAQ},
    "plumbing": {"a": "trade", "kw": ["plumbing", "plumber", "drain", "water heater", "leak"],
                 "cta": "Get a Free Quote", "eyebrow": ["DONE RIGHT, DONE FAST", "24/7 EMERGENCY SERVICE"],
                 "headlines": ["Plumbing you can rely on.", "Fast fixes, fair prices.", "We stop the leak for good."],
                 "about": "Licensed plumbers for repairs, installs, and emergencies — upfront quotes, clean work, and a fix that lasts.",
                 "faq": QUOTE_FAQ},
    "electrician": {"a": "trade", "kw": ["electrician", "electrical", "wiring", "panel", "lighting"],
                    "cta": "Get a Free Quote", "eyebrow": ["SAFE · LICENSED · ON TIME", "POWERED BY TRUST"],
                    "headlines": ["Electrical work done safely.", "Power you can trust.", "Licensed, on time, done right."],
                    "about": "Licensed electricians for repairs, upgrades, and installs — safe, code-compliant work with honest pricing and tidy job sites.",
                    "faq": QUOTE_FAQ},
    "roofing": {"a": "trade", "kw": ["roofing", "roofer", "roof repair", "roof replacement"],
                "cta": "Get a Free Inspection", "eyebrow": ["ROOFS THAT LAST", "FREE INSPECTIONS"],
                "headlines": ["A roof you can count on.", "Repairs and replacements done right.", "Protect what matters most."],
                "about": "Trusted roofing for repairs, replacements, and storm damage — quality materials, expert crews, and workmanship we stand behind.",
                "faq": [("Do you offer free inspections?", "Yes — we'll assess and quote at no cost."),
                        ("Do you handle insurance claims?", "Yes, we'll help you through the process."),
                        ("Are you licensed and insured?", "Fully — details on request.")]},
    "contractor": {"a": "trade", "kw": ["contractor", "construction", "remodeling", "renovation", "builder", "general contractor"],
                   "cta": "Get a Free Estimate", "eyebrow": ["BUILT TO LAST", "ON TIME, ON BUDGET"],
                   "headlines": ["Build it right the first time.", "Remodels done on time, on budget.", "Craftsmanship you can see."],
                   "about": "Full-service contracting for remodels, additions, and new builds — clear timelines, honest budgets, and craftsmanship that lasts.",
                   "faq": [("Do you give free estimates?", "Yes — tell us about your project."),
                           ("Are you licensed and insured?", "Fully licensed, bonded, and insured."),
                           ("How long will my project take?", "We give a realistic timeline up front.")]},
    "landscaping": {"a": "trade", "kw": ["landscaping", "lawn care", "lawn", "landscaper", "yard"],
                    "cta": "Get a Free Quote", "eyebrow": ["CURB APPEAL, DELIVERED", "RELIABLE EVERY WEEK"],
                    "headlines": ["A yard you'll love coming home to.", "Landscaping done right.", "Curb appeal, handled."],
                    "about": "Full-service landscaping and lawn care — design, maintenance, and cleanups by a reliable crew that shows up and does it right.",
                    "faq": QUOTE_FAQ},
    "cleaning": {"a": "trade", "kw": ["cleaning", "house cleaning", "maid", "janitorial", "cleaners"],
                 "cta": "Get a Free Quote", "eyebrow": ["SPOTLESS, EVERY TIME", "TRUSTED & INSURED"],
                 "headlines": ["Come home to clean.", "Spotless, every single time.", "Cleaning you can trust."],
                 "about": "Dependable home and office cleaning — vetted, insured cleaners, a detailed checklist, and a spotless result you can count on.",
                 "faq": [("Are your cleaners insured?", "Yes, vetted and fully insured."),
                         ("Do I need to be home?", "Up to you — many clients give secure access."),
                         ("Do you bring supplies?", "Yes, everything's included.")]},
    "pest-control": {"a": "trade", "kw": ["pest control", "exterminator", "pest", "termite", "rodent"],
                     "cta": "Get a Free Quote", "eyebrow": ["PESTS GONE, GUARANTEED", "SAFE & EFFECTIVE"],
                     "headlines": ["Pests gone. Peace restored.", "Protect your home year-round.", "Safe, effective pest control."],
                     "about": "Effective, family-safe pest control — thorough inspections, targeted treatments, and a guarantee that keeps pests out for good.",
                     "faq": QUOTE_FAQ},
    "painting": {"a": "trade", "kw": ["painting", "painter", "house painting", "interior painting"],
                 "cta": "Get a Free Quote", "eyebrow": ["FLAWLESS FINISHES", "CLEAN, ON-TIME WORK"],
                 "headlines": ["A fresh coat, done flawlessly.", "Color your space beautifully.", "Clean lines, clean work."],
                 "about": "Interior and exterior painting with flawless prep and finish — tidy crews, premium paint, and results that last.",
                 "faq": QUOTE_FAQ},
    "handyman": {"a": "trade", "kw": ["handyman", "home repair", "odd jobs", "honey do"],
                 "cta": "Get a Free Quote", "eyebrow": ["ONE CALL FIXES IT ALL", "RELIABLE & TIDY"],
                 "headlines": ["Your to-do list, handled.", "One call fixes it all.", "Repairs done right."],
                 "about": "Reliable handyman service for repairs, installs, and the whole to-do list — show up on time, do it right, clean up after.",
                 "faq": QUOTE_FAQ},
    "moving": {"a": "trade", "kw": ["moving", "movers", "moving company", "relocation"],
               "cta": "Get a Free Quote", "eyebrow": ["MOVES MADE EASY", "CAREFUL · ON TIME · INSURED"],
               "headlines": ["Moving, made stress-free.", "We handle it with care.", "Your easiest move yet."],
               "about": "Careful, on-time moving for homes and offices — trained crews, the right equipment, and your belongings treated like our own.",
               "faq": [("Do you offer free quotes?", "Yes — tell us where you're headed."),
                       ("Are you insured?", "Yes, fully — your move is protected."),
                       ("Do you pack too?", "Optional packing services available.")]},
    "solar": {"a": "trade", "kw": ["solar", "solar panels", "solar installer", "renewable"],
              "cta": "Get a Free Quote", "eyebrow": ["POWER FROM THE SUN", "SAVE FROM DAY ONE"],
              "headlines": ["Own your power.", "Lower bills, cleaner energy.", "Solar made simple."],
              "about": "Custom solar design and installation — transparent savings estimates, quality panels, and a team that handles permits to power-on.",
              "faq": [("How much will I save?", "We'll model your exact savings for free."),
                      ("Do you handle permits?", "Yes, start to finish."),
                      ("What about financing?", "Multiple options available — ask us.")]},
    "pool": {"a": "trade", "kw": ["pool service", "pool cleaning", "pool", "spa maintenance"],
             "cta": "Get a Free Quote", "eyebrow": ["CRYSTAL-CLEAR, ALWAYS", "RELIABLE WEEKLY SERVICE"],
             "headlines": ["A pool that's always ready.", "Crystal-clear, year-round.", "We handle the upkeep."],
             "about": "Dependable pool cleaning, maintenance, and repair — clear water, balanced chemistry, and a crew that shows up like clockwork.",
             "faq": QUOTE_FAQ},
    "auto": {"a": "trade", "kw": ["auto repair", "mechanic", "auto shop", "car detailing", "detailing", "tire"],
             "cta": "Book Service", "eyebrow": ["HONEST AUTO CARE", "FIXED RIGHT, FIRST TIME"],
             "headlines": ["Auto care you can trust.", "Honest work, fair prices.", "Back on the road, fast."],
             "about": "Straightforward auto repair and service — honest diagnostics, fair pricing, and quality work that keeps you safely on the road.",
             "faq": [("Do you give estimates?", "Yes, before any work begins."),
                     ("Do you offer a warranty?", "Yes on parts and labor — ask for details."),
                     ("How fast can you see my car?", "Often same or next day.")]},

    # PROFESSIONAL SERVICES
    "real-estate": {"a": "professional", "kw": ["real estate", "realtor", "real estate agent", "homes for sale", "broker"],
                    "cta": "Schedule a Call", "eyebrow": ["LOCAL EXPERTISE, REAL RESULTS", "BUY · SELL · INVEST"],
                    "headlines": ["Your move, expertly guided.", "Real estate, done right.", "Find home with confidence."],
                    "about": "Local real estate expertise for buyers and sellers — sharp market knowledge, skilled negotiation, and a smooth process start to finish.",
                    "faq": [("How do we start?", "Book a quick call — we'll map out your goals."),
                            ("What's my home worth?", "Ask for a free, no-obligation valuation."),
                            ("Do you help buyers too?", "Yes, buyers and sellers both.")]},
    "law": {"a": "professional", "kw": ["law", "lawyer", "attorney", "legal", "law firm"],
            "cta": "Request a Consultation", "eyebrow": ["EXPERIENCED · TRUSTED · LOCAL", "FREE CONSULTATION"],
            "headlines": ["Trusted counsel when it matters.", "Your case, in good hands.", "Clear advice, strong results."],
            "about": "Experienced legal representation with a personal touch — clear advice, straight answers, and a team that fights for your outcome.",
            "faq": [("Is the consultation free?", "Yes — your first consultation is at no cost."),
                    ("What areas do you handle?", "Tell us your situation and we'll advise."),
                    ("How are fees structured?", "We'll explain clearly up front.")]},
    "accounting": {"a": "professional", "kw": ["accounting", "accountant", "cpa", "bookkeeping", "tax", "tax preparation"],
                   "cta": "Book a Consultation", "eyebrow": ["NUMBERS, HANDLED", "TAX · BOOKS · ADVICE"],
                   "headlines": ["Your finances, in order.", "Stress-free taxes & books.", "Numbers you can trust."],
                   "about": "Accurate, proactive accounting and tax services for individuals and small businesses — keep your books clean and your taxes optimized.",
                   "faq": [("Do you do both taxes and bookkeeping?", "Yes, plus year-round advice."),
                           ("Do you work with small businesses?", "Absolutely — that's our specialty."),
                           ("How do we get started?", "Book a quick consultation.")]},
    "photography": {"a": "professional", "kw": ["photography", "photographer", "photo studio", "videographer"],
                    "cta": "Check Availability", "eyebrow": ["MOMENTS, BEAUTIFULLY KEPT", "BOOKING NOW"],
                    "headlines": ["Moments worth keeping.", "Your story, beautifully captured.", "Photos you'll treasure."],
                    "about": "Photography that captures the real moments — a relaxed experience and timeless images you'll be proud to display.",
                    "faq": [("How do I book a session?", "Check availability and we'll lock your date."),
                            ("How long until I get photos?", "We'll give you a clear turnaround."),
                            ("Do you travel?", "Yes — ask about your location.")]},
    "interior-design": {"a": "professional", "kw": ["interior design", "interior designer", "home staging", "decor"],
                        "cta": "Book a Consultation", "eyebrow": ["SPACES THAT FEEL LIKE YOU", "DESIGN · STYLE · DETAIL"],
                        "headlines": ["Design that feels like home.", "Spaces, beautifully reimagined.", "Style with substance."],
                        "about": "Thoughtful interior design that balances beauty and livability — spaces tailored to how you actually live, down to the detail.",
                        "faq": [("How does it work?", "It starts with a consultation and a clear plan."),
                                ("Do you work to a budget?", "Yes — we design around your numbers."),
                                ("Full rooms or whole homes?", "Both, plus single-room refreshes.")]},

    # EVENTS
    "venue": {"a": "events", "kw": ["venue", "event venue", "wedding venue", "banquet", "event space"],
              "cta": "Check Availability", "eyebrow": ["UNFORGETTABLE EVENTS START HERE", "NOW BOOKING"],
              "headlines": ["Where moments become memories.", "Your event, beautifully hosted.", "The setting they'll remember."],
              "about": "A stunning, versatile venue for weddings and events — beautiful spaces, flexible packages, and a team that makes your day effortless.",
              "faq": [("How do I check dates?", "Tell us your date and we'll confirm availability."),
                      ("What's your capacity?", "We host a range of sizes — ask for details."),
                      ("Can we tour the space?", "Yes — book a walkthrough.")]},
    "events": {"a": "events", "kw": ["event planning", "event planner", "wedding planner", "party planning", "coordinator"],
               "cta": "Start Planning", "eyebrow": ["EVENTS, EFFORTLESS", "PLANNED TO PERFECTION"],
               "headlines": ["Your event, perfectly planned.", "We handle every detail.", "Celebrate, stress-free."],
               "about": "Full-service event planning that turns your vision into a flawless day — vendor coordination, design, and day-of management handled.",
               "faq": [("How far ahead should I book?", "The earlier the better for prime dates."),
                       ("Do you handle vendors?", "Yes, we coordinate everyone for you."),
                       ("Can you work to a budget?", "Always — we plan around your numbers.")]},

    # TECH / CREATIVE
    "agency": {"a": "tech", "kw": ["agency", "marketing", "design agency", "studio", "saas", "software", "tech", "startup", "consulting"],
               "cta": "Get Started", "eyebrow": ["BUILT TO PERFORM", "RESULTS, NOT EXCUSES"],
               "headlines": ["Growth, engineered.", "Work that moves the needle.", "Built to perform."],
               "about": "A results-driven team that ships work that performs — strategy, design, and execution focused on outcomes you can measure.",
               "faq": [("How do we start?", "Book a call and we'll scope it out."),
                       ("What do you specialize in?", "Tell us your goal — we'll tell you straight."),
                       ("How are projects priced?", "Transparent, scoped, no surprises.")]},
}

# ── derived lookups (built once) ─────────────────────────────────────────────────
ALIASES = {}          # keyword -> canonical
for _canon, _n in NICHES.items():
    ALIASES[_canon] = _canon
    for _kw in _n["kw"]:
        ALIASES[_kw] = _canon

NICHE_WORDS = sorted(set(ALIASES.keys()), key=len, reverse=True)   # longest first = better matching

# per-niche palette overrides where the archetype mood doesn't fit the specific niche
# (barber/tattoo sit in "beauty" but read masculine; landscaping/pool/solar sit in "trade" but read natural)
PALETTE_OVERRIDE = {
    "barber":      ["masculine", "industrial", "bold", "rugged", "dark"],
    "tattoo":      ["bold", "industrial", "masculine", "creative", "dark"],
    "yoga":        ["calm", "natural", "soft", "organic"],
    "landscaping": ["natural", "earthy", "organic", "fresh"],
    "pool":        ["natural", "fresh", "vibrant", "clean"],
    "solar":       ["natural", "fresh", "tech", "clean"],
    "auto":        ["masculine", "industrial", "bold", "rugged"],
    "florist":     ["feminine", "soft", "natural", "elegant"],
    "nails":       ["feminine", "vibrant", "playful", "beauty"],
}
DESIGN_PREFS = {c: {k: ARCHETYPES[n["a"]][k] for k in ("font", "scheme", "layout", "palette")}
                for c, n in NICHES.items()}
for _c, _mood in PALETTE_OVERRIDE.items():
    if _c in DESIGN_PREFS:
        DESIGN_PREFS[_c] = {**DESIGN_PREFS[_c], "palette": _mood}
EFFECT_BIAS = {c: ARCHETYPES[n["a"]]["effects"] for c, n in NICHES.items()}
COPY = {c: {"eyebrow": n["eyebrow"], "headlines": n["headlines"], "cta": n["cta"],
            "about": n["about"], "faq": n["faq"]} for c, n in NICHES.items()}


def resolve(text):
    """Map any niche string to a canonical key (longest keyword match wins). '' if none."""
    if not text:
        return ""
    low = text.lower()
    for kw in NICHE_WORDS:           # longest-first
        if kw in low:
            return ALIASES[kw]
    return ""


if __name__ == "__main__":
    print(f"{len(NICHES)} niches, {len(ALIASES)} keywords, {len(ARCHETYPES)} archetypes")
    for t in ["hvac repair", "med spa botox", "wedding venue", "general contractor remodel",
              "family dentist", "specialty coffee", "roof replacement", "cpa tax", "dog vet"]:
        print(f"  resolve('{t}') -> {resolve(t)}")
